/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Home;

import java.awt.Color;
import java.awt.SplashScreen;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author nilad
 */
public class Aa_Splash extends javax.swing.JFrame {

    /**
     * Creates new form Aa_Splash
     */
    public Aa_Splash() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        progress = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        Tag = new javax.swing.JLabel();
        lper = new javax.swing.JLabel();
        lload = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kGradientPanel1.setkEndColor(new java.awt.Color(102, 255, 102));
        kGradientPanel1.setkStartColor(new java.awt.Color(51, 153, 255));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        progress.setBackground(new java.awt.Color(204, 204, 255));
        progress.setForeground(new java.awt.Color(0, 0, 255));
        kGradientPanel1.add(progress, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 425, 800, 25));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home/tmb_safar.png"))); // NOI18N
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 53, -1, -1));

        Tag.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        Tag.setForeground(new java.awt.Color(0, 0, 153));
        Tag.setText("#Ab Rukna Mana Hai !");
        kGradientPanel1.add(Tag, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 326, -1, -1));

        lper.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        lper.setText("0 %");
        kGradientPanel1.add(lper, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 400, -1, -1));

        lload.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        lload.setText("Loading . . .");
        kGradientPanel1.add(lload, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aa_Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aa_Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aa_Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aa_Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        Aa_Splash ob = new Aa_Splash();
        ob.setVisible(true);     
        try{
            for(int i=0;i<=100;i+=5){
                Thread.sleep(450);
                ob.lper.setText(i +"%");
                if(i==10)
                {
                    ob.lload.setText("Turning on Modules...");
                }
                if(i==30)
                {
                    ob.lload.setText("Loading Modules...");
                }
                if(i==50)
                {
                    ob.lload.setText("Connecting to Database...");
                }
                if(i==70)
                {
                    ob.lload.setText("Connection Successful !");
                }
                if(i==90)
                {
                    ob.lload.setText("Launching Application");
                }
                ob.progress.setValue(i);
            }
                new SignIn().setVisible(true); 
                ob.setVisible(false);
                
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        
    }

   
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Tag;
    private javax.swing.JLabel jLabel1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lload;
    private javax.swing.JLabel lper;
    public static javax.swing.JProgressBar progress;
    // End of variables declaration//GEN-END:variables
}
