/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Home;

/**
 *
 * @author nilad
 */

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Date;
import static java.lang.Math.log;
import java.sql.Blob;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import oracle.jdbc.OracleConnection;
import oracle.jdbc.OracleDriver;
import oracle.jdbc.OraclePreparedStatement;
import oracle.jdbc.OracleStatement;

public class Hotel_Update extends javax.swing.JFrame {

    /**
     * Creates new form Hotel_Update
     */
    public Hotel_Update() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tag = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        bf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fn = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        dcbd = new com.toedter.calendar.JDateChooser();
        bd = new javax.swing.JTextField();
        sc = new javax.swing.JTextField();
        des = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        rt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        rn = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        lPic = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        fid = new javax.swing.JTextField();
        bSEARCH = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kGradientPanel1.setkEndColor(new java.awt.Color(31, 212, 223));
        kGradientPanel1.setkStartColor(new java.awt.Color(247, 15, 255));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("<");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, 28));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Hotel Id");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));
        jPanel1.add(tag, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 300, 28));
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 300, 28));

        jLabel8.setText("Breakfast");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));
        jPanel1.add(bf, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 300, 28));

        jLabel3.setText("Hotel Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel6.setText("Bording Date");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, 15));

        fn.setMinimumSize(new java.awt.Dimension(6, 26));
        jPanel1.add(fn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 300, 28));

        jLabel4.setText("Source");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 20));

        jLabel7.setText("Tag");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jButton3.setText("ADD");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, 80, 55));

        jButton4.setText("DELETE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 110, 80, 55));

        jButton5.setText("UPDATE");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 200, 80, 55));
        jPanel1.add(dcbd, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 145, 28));
        jPanel1.add(bd, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 137, 28));
        jPanel1.add(sc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 300, 28));
        jPanel1.add(des, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 299, 28));

        jLabel1.setText("Description");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, -1, -1));

        jLabel9.setText("Rating");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, 15));
        jPanel1.add(rt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 300, 28));

        jLabel5.setText("Rent");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, -1, -1));
        jPanel1.add(rn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 300, 30));

        jLabel10.setText("Hotel Picture");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, -1, -1));
        jPanel1.add(lPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 300, 150));

        jButton6.setText("Upload");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 340, 70, -1));

        jButton7.setText("Browse");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 300, 70, -1));

        kGradientPanel1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 45, 780, 390));
        kGradientPanel1.add(fid, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 11, 353, 28));

        bSEARCH.setText("Search");
        bSEARCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSEARCHActionPerformed(evt);
            }
        });
        kGradientPanel1.add(bSEARCH, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 11, 75, 28));

        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(509, 11, 75, 28));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Panel().setVisible(true);
            }
        });
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        try {

            //registering the java program with oracle
            DriverManager.registerDriver(new OracleDriver());

            //creating the connection
            OracleConnection oconn= (OracleConnection)DriverManager.getConnection("jdbc:oracle:thin:@FRIDAY:1521:orcl2","techno","morning");

            //creating the statement
            OracleStatement ostmt = (OracleStatement)oconn.createStatement();

            //executing the statement
            SimpleDateFormat sdf = new SimpleDateFormat("dd-MMM-yyyy");
            String k = "insert into hotel (hid, hname, source, dt, ratings, tag, breakfast, description, rent) values ('"+id.getText()+"','"+fn.getText()+"','"+sc.getText()+"','"+sdf.format(dcbd.getDate())+"','"+rt.getText()+"','"+tag.getText()+"','"+bf.getText()+"','"+des.getText()+"','"+rn.getText()+"')";
            JOptionPane.showMessageDialog(this,k);
            ostmt.executeUpdate(k);
            JOptionPane.showMessageDialog(this,"Hotel Data Inserted Successfully !!");

            //clearning text fields
            /*fid.setText("");
            id.setText("");
            fn.setText("");
            sc.setText("");   
            bd.setText("");
            dcbd.setDate(null);
            rt.setText("");
            tag.setText("");
            bf.setText("");
            des.setText("");
            rn.setText("");*/

            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new Show_Flights().setVisible(true);
                }

            });
            dispose();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,ex.toString());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

        if(JOptionPane.showConfirmDialog(this,"Are you sure to delete this Hotel?") == JOptionPane.YES_OPTION)
        {
            try
            {
                // 1. REGISTRATION OF JAVA PROGRAM WITH ORACLE
                DriverManager.registerDriver(new OracleDriver());

                // 2. CREATING THE CONNECTION OBJECT
                OracleConnection oconn =(OracleConnection)DriverManager.getConnection("jdbc:oracle:thin:@FRIDAY:1521:orcl2","techno","morning");

                //3. DECLARING THE VARIABLES
                String vflight;

                // 4. ASSIGNING THE VALUES
                vflight = fid.getText();

                // 5. CREATING THE SQL STATEMENT
                String sql = "delete from hotel where hid = '"+vflight+"'";

                // 6. CREATING THE STATEMENT OBJECT
                OracleStatement ostmt = (OracleStatement)oconn.createStatement();

                // 8. EXECUTING THE DELETE
                ostmt.executeUpdate(sql);

                JOptionPane.showMessageDialog(this,"Hotel deleted successfully");

                //clearning text fields
                fid.setText("");
                id.setText("");
                fn.setText("");
                sc.setText("");
            
                bd.setText("");
                dcbd.setDate(null);
                //rbMALE.setSelected(false);
                //rbFEMALE.setSelected(false);
                rt.setText("");
                tag.setText("");
                bf.setText("");
                des.setText("");
                rn.setText("");
                lPic.setIcon(null);
                //JOptionPane.showMessageDialog(this,"Cleared successfully!");

                ostmt.close();
                oconn.close();
            }
            catch(SQLException ex)
            {
                JOptionPane.showMessageDialog(this,ex.toString());
            }

        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:

        String hotel_id=fid.getText();
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MMM-yyyy");
        try{
            // 1. REGISTRATION OF JAVA PROGRAM WITH ORACLE
            DriverManager.registerDriver(new OracleDriver());

            // 2. CREATING THE CONNECTION OBJECT
            OracleConnection oconn =(OracleConnection)DriverManager.getConnection("jdbc:oracle:thin:@FRIDAY:1521:orcl2","techno","morning");

            // 3. CREATING THE STATEMENT OBJECT
            OracleStatement ostmt = (OracleStatement)oconn.createStatement();
            String sql="Update hotel set hid= ? ,hname=? ,source=? ,dt=? ,ratings=? ,tag=? ,breakfast=? ,description=?, rent=? where hid=?";
            PreparedStatement pst;
            pst = oconn.prepareStatement(sql);

            pst.setString(1, id.getText());
            pst.setString(2, fn.getText());
            pst.setString(3, sc.getText());
            //pst.setString(4, dc.getText());
            pst.setString(4, sdf.format(dcbd.getDate()));
            //pst.setString(3, sdf.format(dcbd.getDate()));
            pst.setString(5, rt.getText());
            pst.setString(6, tag.getText());
            pst.setString(7, bf.getText());
            pst.setString(8, des.getText());
            pst.setString(9, rn.getText());
            pst.setString(10, hotel_id);
            pst.executeUpdate();

            JOptionPane.showMessageDialog(null, "Saved Changes!");
            //dob.setText("");
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new Show_Flights().setVisible(true);
                }
            });
            /*hospitalNameCombo.removeAllItems();
            fillcombo();
            conn.close();
            btn_Save.setEnabled(false);
            btn_Search.setEnabled(true);
            hospitalNameCombo.setEnabled(true);*/
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        //log ob=new log();
        //ob.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void bSEARCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSEARCHActionPerformed
        // TODO add your handling code here:

        try {
            // 1. REGISTRATION OF JAVA PROGRAM WITH ORACLE
            DriverManager.registerDriver(new OracleDriver());

            // 2. CREATING THE CONNECTION OBJECT
            OracleConnection oconn =(OracleConnection)DriverManager.getConnection("jdbc:oracle:thin:@FRIDAY:1521:orcl2","techno","morning");

            // 3. CREATING THE STATEMENT OBJECT
            OracleStatement ostmt = (OracleStatement)oconn.createStatement();

            String sql = "Select * from hotel where hid=?";
            String flight_id;
            PreparedStatement pst;
            pst = oconn.prepareStatement(sql);
            flight_id = fid.getText();

            pst.setString(1,flight_id);

            ResultSet rs = pst.executeQuery();

            if(rs.next()) {
                
                Blob b = rs.getBlob("IMAGE");
                        byte barr[] = b.getBytes(1, (int)b.length());
                        FileOutputStream fos = new FileOutputStream("d:\\temp"+fid.getText()+".jpg");
                        fos.write(barr);
                        BufferedImage bi;
                        bi = ImageIO.read(new File("d:\\temp"+fid.getText()+".jpg"));
                        Image i = bi.getScaledInstance(lPic.getWidth(), lPic.getHeight(),Image.SCALE_SMOOTH);
                        ImageIcon ii = new ImageIcon(i);
                        lPic.setIcon(ii);

                id.setText(rs.getString("hid"));
                fn.setText(rs.getString("hname"));
                sc.setText(rs.getString("source"));
                //dc.setText(rs.getString("destination"));

                SimpleDateFormat dt2 = new SimpleDateFormat("yyyyy-mm-dd hh:mm:ss");
                Date date = dt2.parse(rs.getString(4));
                SimpleDateFormat dt1 = new SimpleDateFormat("dd-MMM-yyyy");
                bd.setText(dt1.format(date));

                //SimpleDateFormat dt1 = new SimpleDateFormat("dd-MMM-yyyy");
                //bd.setText(dt1.format(5));
                //dcDOB.setDateFormatString(dt1.format(3));

                rt.setText(rs.getString("ratings"));
                tag.setText(rs.getString("tag"));
                bf.setText(rs.getString("breakfast"));
                des.setText(rs.getString("description"));
                rn.setText(rs.getString("rent"));

            }
            else {
                JOptionPane.showMessageDialog(null, "Sorry record not found!!");
            }
            oconn.close();

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_bSEARCHActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        //clearning text fields
        fid.setText("");
        id.setText("");
        fn.setText("");
        sc.setText("");
            
        bd.setText("");
        dcbd.setDate(null);
        //rbMALE.setSelected(false);
        //rbFEMALE.setSelected(false);
        rt.setText("");
        tag.setText("");
        bf.setText("");
        des.setText("");
        rn.setText("");
        lPic.setIcon(null);
        JOptionPane.showMessageDialog(this,"Cleared successfully!");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        try
            {
                // 1. REGISTRATION OF JAVA PROGRAM WITH ORACLE
                DriverManager.registerDriver(new OracleDriver());

                //3. DECLARING THE VARIABLES
                // 2. CREATING THE CONNECTION OBJECT
                        OracleConnection oconn = (OracleConnection)DriverManager.getConnection("jdbc:oracle:thin:@FRIDAY:1521:orcl2","techno","morning") ;
                    //3. DECLARING THE VARIABLES
                    String vEmail;
                    
                    // 4. ASSIGNING THE VALUES
                    vEmail = fid.getText();
                    // 5. CREATING THE SQL STATEMENT
                    String sql = " update hotel set image=? where hid=?";
                    
                     // 6. CREATING THE STATEMENT OBJECT
                            OraclePreparedStatement ostmt = (OraclePreparedStatement)oconn.prepareStatement(sql) ;
                            //JOptionPane.showMessageDialog(this,pather);
                            FileInputStream istr = new FileInputStream(pather);
                            ostmt.setBinaryStream(1,istr,istr.available());
                        
                            ostmt.setString(2, vEmail);
                        
                        // 8. EXECUTING THE UPDATE
                        int x;
                        x = ostmt.executeUpdate();
                        if (x != 1) {
                        } else {
                            JOptionPane.showMessageDialog(this,"User pic added successfully");
                        }
                    }     
            catch(SQLException | FileNotFoundException ex)
            {
                JOptionPane.showMessageDialog(this,ex.toString());
            } catch (IOException ex) {
            JOptionPane.showMessageDialog(this,ex.toString());
            }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser("C:\\Windows\\Web\\Wallpaper\\Theme2\\");
        int x = fc.showOpenDialog(this);
        if(x == JFileChooser.APPROVE_OPTION)
        {
            try {
                       pather = fc.getSelectedFile().getAbsolutePath();
            BufferedImage bi;
                bi = ImageIO.read(new File(pather));
           
            Image i = bi.getScaledInstance(lPic.getWidth(), lPic.getHeight(),Image.SCALE_SMOOTH);
            ImageIcon ii = new ImageIcon(i);
            lPic.setIcon(ii);
             } catch (IOException ex) {
                JOptionPane.showMessageDialog(this,ex.toString());
            }
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hotel_Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hotel_Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hotel_Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hotel_Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hotel_Update().setVisible(true);
            }
        });
    }
    
    private static String pather;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bSEARCH;
    private javax.swing.JTextField bd;
    private javax.swing.JTextField bf;
    private com.toedter.calendar.JDateChooser dcbd;
    private javax.swing.JTextField des;
    private javax.swing.JTextField fid;
    private javax.swing.JTextField fn;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lPic;
    private javax.swing.JTextField rn;
    private javax.swing.JTextField rt;
    private javax.swing.JTextField sc;
    private javax.swing.JTextField tag;
    // End of variables declaration//GEN-END:variables
}
