/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Home;

import java.util.Date;
import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Blob;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import oracle.jdbc.OracleConnection;
import oracle.jdbc.OracleDriver;
import oracle.jdbc.OraclePreparedStatement;
import oracle.jdbc.OracleResultSet;
import oracle.jdbc.OracleStatement;


/**
 *
 * @author mohit
 */
public class MyProfile extends javax.swing.JFrame {

    /**
     * Creates new form MyProfile
     */
    public MyProfile() {
        initComponents();
        if(c.getText().trim().equals(""))
        {

            c.grabFocus();
            return;
        }
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgGender = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lPic = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        bUPLOAD = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lem = new javax.swing.JTextField();
        lpass = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        nm = new javax.swing.JTextField();
        c = new javax.swing.JTextField();
        dcdob = new org.netbeans.modules.form.InvalidComponent();
        rbMALE = new javax.swing.JRadioButton();
        rbFEMALE = new javax.swing.JRadioButton();
        dob = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        lph = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        kGradientPanel1 = new org.netbeans.modules.form.InvalidComponent();
        jButton10 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        tfEM = new javax.swing.JTextField();
        clear = new javax.swing.JButton();
        search = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1350, 800));
        setMinimumSize(new java.awt.Dimension(1350, 800));
        setPreferredSize(new java.awt.Dimension(1350, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lPic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 200, 200));

        jButton12.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jButton12.setText("+ Log Out");
        jButton12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 153, 255), new java.awt.Color(51, 0, 204), null, new java.awt.Color(153, 255, 51)));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 570, 109, 45));

        bUPLOAD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bUPLOAD.setText("Upoad");
        bUPLOAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUPLOADActionPerformed(evt);
            }
        });
        jPanel1.add(bUPLOAD, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, 35));

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setText("Browse");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, -1, 35));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 300, 660));

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lemActionPerformed(evt);
            }
        });
        jPanel3.add(lem, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 390, 40));
        jPanel3.add(lpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 390, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setText("Login Details");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Manage yourr email id, mobile number and password");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel25.setText("Email");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel20.setText("Password");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton6.setText("Update");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 160, 140, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 540, 990, 240));

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setText("Birthday");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 155, -1, 30));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setText("Gender");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 205, -1, 40));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel21.setText("Name");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        nm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nmFocusGained(evt);
            }
        });
        nm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nmActionPerformed(evt);
            }
        });
        jPanel4.add(nm, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 390, 40));

        c.setFocusable(false);
        c.setRequestFocusEnabled(false);
        c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cActionPerformed(evt);
            }
        });
        jPanel4.add(c, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 390, 40));
        jPanel4.add(dcdob, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 190, 40));

        bgGender.add(rbMALE);
        rbMALE.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbMALE.setText("Male");
        jPanel4.add(rbMALE, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 80, 30));

        bgGender.add(rbFEMALE);
        rbFEMALE.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbFEMALE.setText("Female");
        rbFEMALE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFEMALEActionPerformed(evt);
            }
        });
        jPanel4.add(rbFEMALE, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 80, 30));
        jPanel4.add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 180, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel7.setText("Profile");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Basic Info for a faster booking experience");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel27.setText("Country");
        jPanel4.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, -1, -1));

        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton7.setText("Save Changes");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 320, 140, 40));

        lph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lphActionPerformed(evt);
            }
        });
        jPanel4.add(lph, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 390, 40));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel26.setText("Mobile Number");
        jPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 990, 400));

        kGradientPanel1.null;

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home/back_small.png"))); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Connect");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("Explore");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setText("My Profile");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 985, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, -1));

        tfEM.setText("Enter your email...");
        tfEM.setToolTipText("");
        tfEM.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tfEM.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfEMFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfEMFocusLost(evt);
            }
        });
        tfEM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEMActionPerformed(evt);
            }
        });
        getContentPane().add(tfEM, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 70, 362, 40));

        clear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 70, 80, 40));

        search.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 70, 80, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nmActionPerformed

    private void cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cActionPerformed

    private void lemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lemActionPerformed

    private void lphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lphActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lphActionPerformed

    private void tfEMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEMActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_tfEMActionPerformed

    private void tfEMFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfEMFocusGained
        // TODO add your handling code here:
         if(tfEM.getText().equals("Enter your email..."))
        {
            tfEM.setText("");
            tfEM.setForeground(new Color(0,0,0));
            //tfTYPENAME.setBackground(new Color(153,153,153));
        }
    }//GEN-LAST:event_tfEMFocusGained

    private void tfEMFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfEMFocusLost
        // TODO add your handling code here:
        
        if(tfEM.getText().equals(""))
        {
            tfEM.setText("Enter your email...");
            tfEM.setForeground(new Color(153,153,153));
        }
    
    }//GEN-LAST:event_tfEMFocusLost

    private void nmFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nmFocusGained
        // TODO add your handling code here:
         if(nm.getText().equals("Enter your email..."))
        {
            nm.setText("");
            nm.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_nmFocusGained

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Flight_Home().setVisible(true);
            }
        });
        dispose();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new connect_fresh().setVisible(true);
            }
        });
        dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new explore1().setVisible(true);
            }
        });
        dispose();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyProfile().setVisible(true);
            }
        });
        dispose();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser("C:\\Windows\\Web\\Wallpaper\\Theme2\\");
        int x = fc.showOpenDialog(this);
        if(x == JFileChooser.APPROVE_OPTION)
        {
            try {
                       pather = fc.getSelectedFile().getAbsolutePath();
            BufferedImage bi;
                bi = ImageIO.read(new File(pather));
           
            Image i = bi.getScaledInstance(lPic.getWidth(), lPic.getHeight(),Image.SCALE_SMOOTH);
            ImageIcon ii = new ImageIcon(i);
            lPic.setIcon(ii);
             } catch (IOException ex) {
                JOptionPane.showMessageDialog(this,ex.toString());
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void bUPLOADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUPLOADActionPerformed
        // TODO add your handling code here:
        try
            {
                // 1. REGISTRATION OF JAVA PROGRAM WITH ORACLE
                DriverManager.registerDriver(new OracleDriver());

                //3. DECLARING THE VARIABLES
                // 2. CREATING THE CONNECTION OBJECT
                        OracleConnection oconn = (OracleConnection)DriverManager.getConnection("jdbc:oracle:thin:@FRIDAY:1521:orcl2","techno","morning") ;
                    //3. DECLARING THE VARIABLES
                    String vEmail;
                    
                    // 4. ASSIGNING THE VALUES
                    vEmail = tfEM.getText();
                    // 5. CREATING THE SQL STATEMENT
                    String sql = " update users set image=? where uemail=?";
                    
                     // 6. CREATING THE STATEMENT OBJECT
                            OraclePreparedStatement ostmt = (OraclePreparedStatement)oconn.prepareStatement(sql) ;
                            //JOptionPane.showMessageDialog(this,pather);
                            FileInputStream istr = new FileInputStream(pather);
                            ostmt.setBinaryStream(1,istr,istr.available());
                        
                            ostmt.setString(2, vEmail);
                        
                        // 8. EXECUTING THE UPDATE
                        int x;
                        x = ostmt.executeUpdate();
                        if (x != 1) {
                        } else {
                            JOptionPane.showMessageDialog(this,"User pic added successfully");
                        }
                    }     
            catch(SQLException | FileNotFoundException ex)
            {
                JOptionPane.showMessageDialog(this,ex.toString());
            } catch (IOException ex) {
            JOptionPane.showMessageDialog(this,ex.toString());
            }
    }//GEN-LAST:event_bUPLOADActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        tfEM.setText("");
        nm.setText("");
        nm.setText("");
        dob.setText("");
        dcdob.setDate(null);
        rbMALE.setSelected(false);
        rbFEMALE.setSelected(false);
        c.setText("");
        lem.setText("");       
        lph.setText("");
        lpass.setText("");
        lPic.setIcon(null);
        JOptionPane.showMessageDialog(this,"Cleared successfully!");
    }//GEN-LAST:event_clearActionPerformed

    private void rbFEMALEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFEMALEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbFEMALEActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        try
        {
            // 1. REGISTRATION OF JAVA PROGRAM WITH ORACLE
            DriverManager.registerDriver(new OracleDriver());
            
            // 6. CREATING THE SQL STATEMENT
            // 2. CREATING THE CONNECTION OBJECT
                    OracleConnection oconn = (OracleConnection)DriverManager.getConnection("jdbc:oracle:thin:@FRIDAY:1521:orcl2","techno","morning");
                // 6. CREATING THE SQL STATEMENT
                String sql = "select * from users where uemail=?";
                
                // 7. EXECUTING THE SELECT
                 // 3. CREATING THE STATEMENT OBJECT                        
                        String email;
                        PreparedStatement pst;
                        pst = oconn.prepareStatement(sql);
                        email = tfEM.getText();

                        pst.setString(1,email);

                        ResultSet ors = pst.executeQuery();
                        
                    if(ors.next())
                    {
                        Blob b = ors.getBlob("IMAGE");
                        byte barr[] = b.getBytes(1, (int)b.length());
                        FileOutputStream fos = new FileOutputStream("d:\\temp"+tfEM.getText()+".jpg");
                        fos.write(barr);
                        BufferedImage bi;
                        bi = ImageIO.read(new File("d:\\temp"+tfEM.getText()+".jpg"));
                        Image i = bi.getScaledInstance(lPic.getWidth(), lPic.getHeight(),Image.SCALE_SMOOTH);
                        ImageIcon ii = new ImageIcon(i);
                        lPic.setIcon(ii);
                        
                        //other data inserting
                        
                        nm.setText(ors.getString("uname"));
                        lem.setText(ors.getString("uemail"));

                        //SimpleDateFormat dt2 = new SimpleDateFormat("yyyyy-mm-dd hh:mm:ss");
                        //Date date = dt2.parse(ors.getString(3));
                        //SimpleDateFormat dt1 = new SimpleDateFormat("dd-MMM-yyyy");
                        //dob.setText(dt1.parse(ors.getDate(3)).toString());

                        
                        SimpleDateFormat dt = new SimpleDateFormat("yyyyy-mm-dd hh:mm:ss"); 
                        Date date = dt.parse(ors.getString(3)); 
                        SimpleDateFormat dt1 = new SimpleDateFormat("dd-MMM-yyyy"); 
                        dob.setText(dt1.format(date));
                        
                        
                        lph.setText(ors.getString("uph"));

                        if(ors.getString(5).equals("M"))
                        {
                            rbMALE.setSelected(true);
                        }
                        else
                        {
                            rbFEMALE.setSelected(true);
                        }
                        c.setText(ors.getString("ucountry"));
                        lpass.setText(ors.getString("upass"));
                    }
                    ors.close();
                    pst.close();
                    oconn.close();
                    
                }
        catch(SQLException | FileNotFoundException ex)
        {
            JOptionPane.showMessageDialog(this,ex.toString());
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this,ex.toString());
        }
        catch (ParseException ex) {
            JOptionPane.showMessageDialog(this,ex.toString());
        }
    }//GEN-LAST:event_searchActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        String email=tfEM.getText();
        
        //SimpleDateFormat dt2 = new SimpleDateFormat("yyyyy-mm-dd hh:mm:ss");
        //Date date = dt2.parse(ors.getString(3));
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MMM-yyyy");
        
        try{
            // 1. REGISTRATION OF JAVA PROGRAM WITH ORACLE
            
            DriverManager.registerDriver(new OracleDriver());

            // 2. CREATING THE CONNECTION OBJECT
            OracleConnection oconn =(OracleConnection)DriverManager.getConnection("jdbc:oracle:thin:@FRIDAY:1521:orcl2","techno","morning");

            // 3. CREATING THE STATEMENT OBJECT
            OracleStatement ostmt = (OracleStatement)oconn.createStatement();
            String sql="Update users set uname= ? ,udob=? ,uph=? ,ugender=? ,ucountry=? where uemail=?";
            PreparedStatement pst;
            pst = oconn.prepareStatement(sql);

            
            
            pst.setString(1, nm.getText());
            pst.setString(2, sdf.format(dcdob.getDate()));
            pst.setString(3, lph.getText());
            pst.setString(4, rbMALE.isSelected()?"M":"F");
            pst.setString(5, c.getText());
            pst.setString(6, email);
            pst.executeUpdate();

            JOptionPane.showMessageDialog(null, "Saved Changes!");
            //dob.setText("");
            /*hospitalNameCombo.removeAllItems();
            fillcombo();
            conn.close();
            btn_Save.setEnabled(false);
            btn_Search.setEnabled(true);
            hospitalNameCombo.setEnabled(true);*/
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        //log ob=new log();
        //ob.setVisible(true);
        //setVisible(false);
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyProfile().setVisible(true);
            }
        });
        dispose();
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String email=tfEM.getText();
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MMM-yyyy");
        try{
            // 1. REGISTRATION OF JAVA PROGRAM WITH ORACLE
            DriverManager.registerDriver(new OracleDriver());

            // 2. CREATING THE CONNECTION OBJECT
            OracleConnection oconn =(OracleConnection)DriverManager.getConnection("jdbc:oracle:thin:@FRIDAY:1521:orcl2","techno","morning");

            // 3. CREATING THE STATEMENT OBJECT
            OracleStatement ostmt = (OracleStatement)oconn.createStatement();
            String sql="Update users set uemail= ? ,upass=? where uemail=?";
            PreparedStatement pst;
            pst = oconn.prepareStatement(sql);

            pst.setString(1, lem.getText());
            pst.setString(2, String.valueOf(lpass.getPassword()));
            pst.setString(3, email);
            pst.executeUpdate();

            JOptionPane.showMessageDialog(null, "Saved Changes!");
            //dob.setText("");
            /*hospitalNameCombo.removeAllItems();
            fillcombo();
            conn.close();
            btn_Save.setEnabled(false);
            btn_Search.setEnabled(true);
            hospitalNameCombo.setEnabled(true);*/
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        //log ob=new log();
        //ob.setVisible(true);
        //setVisible(false);
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyProfile().setVisible(true);
            }
        });
        dispose();
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignIn().setVisible(true);
            }
        });
        dispose();
    }//GEN-LAST:event_jButton12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyProfile().setVisible(true);
            }
        });
    }
    
    private static String pather;
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bUPLOAD;
    private javax.swing.ButtonGroup bgGender;
    private javax.swing.JTextField c;
    private javax.swing.JButton clear;
    private org.netbeans.modules.form.InvalidComponent dcdob;
    private javax.swing.JTextField dob;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private org.netbeans.modules.form.InvalidComponent kGradientPanel1;
    private javax.swing.JLabel lPic;
    private javax.swing.JTextField lem;
    private javax.swing.JPasswordField lpass;
    private javax.swing.JTextField lph;
    private javax.swing.JTextField nm;
    private javax.swing.JRadioButton rbFEMALE;
    private javax.swing.JRadioButton rbMALE;
    private javax.swing.JButton search;
    private javax.swing.JTextField tfEM;
    // End of variables declaration//GEN-END:variables
}
